services:
  - type: web
    name: instagram-frontend
    env: static
    buildCommand: npm ci --legacy-peer-deps && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
