services:
  - type: web
    name: instagram-frontend
    env: static
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
